### ISSUE TITLE
Infinite loop.....

### ISSUE THREAD

**Issue by danoyoung** [grantr/rubberband#10]
I'm working with a single node ES instance, and I'm trying to figure out how to check to see if the node is up and if not, raise an exception. Currently if my node is down, my request just hangs.... I know most of the time ES will be running in a cluster, but it seems that rubberband gets in an infinite loop if the server is not up. I believe I'v tracked it down to these two methods....when debugging I can see that the @live_server_list is empty...and the execute method just keeps on retrying......

Is this a bug?  I'm using 0.0.7.

 def disconnect!
      # Keep live servers in the list if we have a retry period. Otherwise,
      # always eject, because we will always re-add them.
      if @retry_period && @current_server
        @live_server_list.unshift(@current_server)
      end

```
  super
  @request_count = 0
end
```

def execute(method_name, *args)
      disconnect_on_max! if @max_requests and @request_count >= @max_requests
      @request_count += 1
      begin
        super
      rescue ElasticSearch::RetryableError
        disconnect!
        retry
      end
    end
end

**Comment by grantr** [comment]
This is definitely a bug, and it's a bad one. I've been meaning to fix it for a while but haven't gotten around to it. If you feel like submitting a pull request it would be appreciated! :)

**Comment by danoyoung** [comment]
Should I do this via a pull request?  I'm a bit new to this github pull request model.....I'm willing to give it a shot though.

**Comment by grantr** [comment]
It's easy. Just fork the project, push new stuff to your fork, and click pull request. Definitely give it a shot!

**Comment by dhruvbansal** [comment]
A fix is to make ConnectionFailed subclass FatalError instead of RetryableError.  This is fixed in my fork (and you have a pull request ;)

**Comment by grantr** [comment]
fixed thanks to dhruvbansal in 89d19185a01aef8eda84f60e2b2327529397abea
