### ISSUE TITLE
Question on POSTing.

### ISSUE THREAD

**Issue by danoyoung** [grantr/rubberband#11]
I'm interested in storing child documents in ElasticSearch.  Typically via CURL it is done like this:
curl -XPUT 'localhost:9200/sizonet/ice/1?parent=882e7190-1b47-012e-e618-34159e27f1f2' -d '
{"tag" : "frozen"}'

so I'm wondering how/if I can add the ?parent= to a rubberband request?

**Comment by grantr** [comment]
You can pass arbitrary options to the index method:

```
client.index({:tag => 'frozen'}, :id => 1, :parent => "882e7190-1b47-012e-e618-34159e27f1f2")
```

This is only possible in 0.0.7 and up due to #8

**Comment by danoyoung** [comment]
sweet, thank you.  Worked like a champ.
