### ISSUE TITLE
Hash#select returns hash in 1.9.x but array in 1.8.x

### ISSUE THREAD

**Issue by kennon** [grantr/rubberband#13]
In grantr/rubberband@73700e902c0b62e27a8195b21a1bf34b1c69c043 #L0R75
you added a call to "options.select" which returns a hash as expected in Ruby 1.9.2, but in 1.8.7 it returns an array which causes a "Symbol as array index" exception.

Is there a way to test for ruby 1.9.2 or should we check to see if it's really still a hash or not? What's the best way to solve this for us plebes still running 1.8.7?

**Comment by grantr** [comment]
Oops, didn't realize this. Will push a fix soon. Thanks for the report!

**Comment by grantr** [comment]
Hash#select returns an array in 1.8

closed by c17ed3aef1a9a37c37d168c991ad84b8f4dea655
