### ISSUE TITLE
Test fail spec/type_spec.rb

### ISSUE THREAD

**Issue by jeroig** [grantr/rubberband#14]
Hi Grant, 

I found a fail test in spec/type_spec.rb, i search in deep and discover that the problem was elasticsearch, so i open a issue and the bug was fix.
( https://github.com/elasticsearch/elasticsearch/issues/839#comment_968696 ) . In future versions of elasticsearch the test will pass correctly.

Regars
Jeroig

**Comment by grantr** [comment]
Great work! I'll close this issue for now but feel free to reopen if anything else is required.
