### ISSUE TITLE
Indexing JSON Document vs. Text

### ISSUE THREAD

**Issue by lobster1234** [grantr/rubberband#17]
Hi there - not sure if I am missing something, but when I tried to index a JSON document, it ended up being indexed as a String. Does the API only support text/strings right now and not JSON data?

`response = @client.index({:person => JSON.generate(my_hash)}, :id => id)`

`my_hash` is a key-value hash. The indexed document ends up having the entire JSON string as 1 field instead of the key-values.

**Comment by grantr** [comment]
Rubberband expects documents to be hashes; JSON encoding is handled internally. You are sending a document with a single string value, so it is indexing a string value.

do this instead:

``` ruby
@client.index({:person => my_hash}, :id => id)
```

**Comment by lobster1234** [comment]
Awesome! Thanks so much, it works like a charm :)
