### ISSUE TITLE
Invalid gemspec date

### ISSUE THREAD

**Issue by jgeiger** [grantr/rubberband#18]
Invalid gemspec in [/Users/user/workspace/app/vendor/bundle/ruby/1.9.1/specifications/rubberband-0.0.11.gemspec]: invalid date format in specification: "2011-04-25 00:00:00.000000000Z"
Could not find rubberband-0.0.11 in any of the sources

gem -v
1.7.2

It seems that when installing the gem via bundler, it's converting the data in the gemspec into that much longer string. This causes it to become invalid and fails to load.

This may be a rubygems bug, but I've not run into it on any other gem, and I noticed that you're in the middle of a jeweler to bundler conversion which may be causing the issue.

Editing the installed file to match the repository version allows it to work again.

**Comment by grantr** [comment]
Just pushed a new version (0.0.12) that switches to bundler and hopefully fixes the date issue. Let me know if you still have issues.
