### ISSUE TITLE
Problem adding a document to a new index

### ISSUE THREAD

**Issue by gjb83** [grantr/rubberband#21]
Environment:
ES v0.16.0 with rubberband v0.0.12

I am finding that if I add a document to a non-existent index, the index is automatically created, but around 50% of the time, the document is not added.

Steps to reproduce:

```
> es = ElasticSearch.new('127.0.0.1:9200', index: 'myindex', type: 'mytype')

> es.delete_index('myindex')
=> {"ok"=>true, "acknowledged"=>true}

> es.index({body: 'Test'})
=> "0T4rler5SF-DbDr_BN48nw"

> es.refresh 
=> {"ok"=>true, "_shards"=>{"total"=>10, "successful"=>5, "failed"=>0}}

> es.get("0T4rler5SF-DbDr_BN48nw")
=> nil

# A manual check of http://localhost:9200/myindex/mytype/0T4rler5SF-DbDr_BN48nw confirms that
# no document with this id exists in the index.
```

You may have to delete the index and repeat this process a few times to reproduce this problem as it doesn't happen every time. It is also worth noting that with the index in this state, subsequent documents can be added without this problem occurring.

**Comment by grantr** [comment]
This seems suspiciously like an elasticsearch bug. As long as you get a successful response from elasticsearch, rubberband has done its job.

Have you tried reproducing this with a new index that hasn't been deleted recently? Elasticsearch may be dropping the document because it is still deleting the index.

**Comment by gjb83** [comment]
I have just run exactly the same test directly against elasticsearch, and you are absolutely right: this is an elasticsearch bug.

Many thanks.

**Comment by grantr** [comment]
Thanks! I'm sure Shay would appreciate a bug report :)

**Comment by gjb83** [comment]
I'll post a link to my elasticsearch bug report here just in case anyone else comes up against the same issue and tries to blame you :)

http://github.com/elasticsearch/elasticsearch/issues/931
