### ISSUE TITLE
Previewing a request

### ISSUE THREAD

**Issue by gjb83** [grantr/rubberband#22]
Not an issue as such, but more a question.

Is it possible to preview the JSON and endpoint for a request generated by Rubberband before it is sent to ES?

Many thanks.

**Comment by grantr** [comment]
There is no way to do this currently. 

One thing I could do is add a transport that takes a block and calls that block with each request. You could then inspect the request or log it or whatever inside your block. This transport would not actually submit the request, it would only generate it for inspection purposes.

Would this solve your use case?

**Comment by grantr** [comment]
Btw, for a quick and dirty hack, you can uncomment the puts call in the http transport, but don't tell anyone that it's there! :)

**Comment by gjb83** [comment]
Thanks, that is certainly a big help. It's always good to be able to find out what is going on under the hood.
