### ISSUE TITLE
Invalid date format for gemspec in 0.0.12

### ISSUE THREAD

**Issue by dhruvbansal** [grantr/rubberband#25]
I noticed that the gemspec that is generated when installing rubberband 0.0.12 (typically in `/usr/lib/ruby/gems/1.8/specifications/rubberband-0.0.12`) has an invalid format for the date:

```
s.authors = ["Grant Rodgers"]
s.date = %q{2011-04-28 00:00:00.000000000Z}
s.description = %q{An ElasticSearch client with ThriftClient-like failover handling.}
```

It should read

```
s.authors = ["Grant Rodgers"]
s.date = %q{2011-04-28}
s.description = %q{An ElasticSearch client with ThriftClient-like failover handling.}
```

This causes problems with later versions of RubyGems & Bundler (I'm seeing it with gems 1.8.5 & bundler 1.0.10) as RubyGems refuses to load rubberband with the following error

```
Invalid gemspec in [/usr/lib/ruby/gems/1.8/specifications/rubberband-0.0.12.gemspec]: invalid date format in specification: "2011-04-28 00:00:00.000000000Z"
```

which means Bundler can't find the Gem and your app won't boot :(

**Comment by grantr** [comment]
I'm not able to repro this, but can you try updating to 0.1.1 and see if that fixes the issue?

**Comment by dhruvbansal** [comment]
I see the same problem in 0.1.1 :(. 

To reproduce:
1. Make sure you're using RubyGems >= 1.7.2
2. Uninstall all rubberband gems
3. Install rubberband-0.1.1
4. Run the following

```
#!/usr/bin/env ruby
require 'rubygems'
require 'rubberband'
```

When I try this I see warnings like 

```
Invalid gemspec in [/usr/lib/ruby/gems/1.8/specifications/rubberband-0.1.1.gemspec]: invalid date format in specification: "2011-06-20 00:00:00.000000000Z"
```

and then I get a `LoadError` when trying to `require "rubberband"` b/c RubyGems refuses to let it load b/c of the invalid date format.

Again, everything works just fine if I manually edit the date format in `rubberband-0.1.1.gemspec` to `2011-06-20`.  What are you using to create your gemspec file?

**Comment by grantr** [comment]
The gemspec is not generated, it is edited manually. I followed your repro steps but didn't get any errors. What version of Ruby are you using?

 more /usr/lib/ruby/gems/1.8/specifications/rubberband-0.1.1.gemspec | grep date
  s.date = %q{2011-06-20}

**Comment by grantr** [comment]
Oops, didn't mean to close yet

**Comment by dhruvbansal** [comment]
Still happening to me...but it appears that this is a RubyGems issue: https://github.com/rubygems/rubygems/pull/57

Thanks grant!

**Comment by grantr** [comment]
Thanks for investigating!
