### ISSUE TITLE
Should support ELASTICSEARCH_URL env var for easier Heroku integration

### ISSUE THREAD

**Issue by nz** [grantr/rubberband#31]
Hey @grantr,

There is an ElasticSearch addon now in alpha at Heroku which provides the ELASTICSEARCH_URL environment variable to specify to the app where the index lives. Is there a way for rubberband to facilitate easier integration for Heroku apps that want to use rubberband?

For instance, it would be convenient if rubberband could accept an unparsed string for the URL. An [RSolr](http://github.com/mwmitchell/rsolr)-esque approach might work well here:

``` ruby
client = ElasticSearch.connect url: ENV['ELASTICSEARCH_URL']
```

Of course, working that into the initializer would be even nicer…

``` ruby
client = ElasticSearch.new(ENV['ELASTICSEARCH_URL'])
```

Anyway, just thinking out loud here. What are your thoughts?

—Nick

**Comment by grantr** [comment]
If Heroku has an elasticsearch addon in the works, it would be awesome to support that. What is the format of the ELASTICSEARCH_URL variable?

**Comment by nz** [comment]
Something like `http://index.bonsai.io/68ylsz4xkd77xtvqz` — so that's the scheme, host, port, and index name.

**Comment by nz** [comment]
Also if you want in on that alpha, I can set that up. Just send me a message with a Heroku account email address :)

**Comment by grantr** [comment]
Ok, if the index is in the url that will not work at present, but it's worth adding.

**Comment by nz** [comment]
Yeah, I guess that's really the crux of the question here, since the addon pretty strongly assumes one index per application per environment.

**Comment by grantr** [comment]
I will probably implement it by allowing default index scope to be set in client initialize. Every operation (with a couple exceptions that will be updated) uses the default index if none is specified.
