### ISSUE TITLE
Mechanism to see the actual JSON sent to and received from ElasticSearch

### ISSUE THREAD

**Issue by konklone** [grantr/rubberband#37]
One very helpful feature would be a way to expose the final JSON that was constructed and sent to ElasticSearch, and the JSON that ElasticSearch responded with. 

I use rubberband behind a production API, and I use an "explain" mode in the API to help me diagnose issues. Currently, I can show the hash of options I gave to rubberband, and the response hash that rubberband shows me, but they're not the same as the actual ES transport data. 

This would greatly ease debugging, and posting recreations of issues for support.

**Comment by grantr** [comment]
This would definitely be useful. Would it be helpful to provide an 'explain' option to commands that returns the json that would be sent instead of submitting to elasticsearch?

**Comment by konklone** [comment]
That would be a great feature, especially for testing out expensive queries without running them. I think you would still want to support some sort of introspection on Rubberband's response objects, though - both what was sent and what was returned.

**Comment by grantr** [comment]
@konklone, I just changed rubberband to use faraday for http requests. You can use middleware to add whatever introspection you want to the request and response.

``` ruby
require 'rubberband'
require 'logger'

class BodyLogger < Faraday::Response::Middleware
  LOGGER = Logger.new(STDOUT)

  def call(env)
    LOGGER.info("request body: #{env[:body]}")
    super
  end

  def on_complete(env)
    LOGGER.info("response body: #{env[:body]}")
  end
end
Faraday.register_middleware :response, :body_logger => BodyLogger

c = ElasticSearch::Client.new('127.0.0.1:9200') do |conn|
  conn.response :body_logger
  conn.adapter Faraday.default_adapter
end
```

Unfortunately this only works for the http transport, but that's probably what you're debugging anyway.

**Comment by konklone** [comment]
This definitely improves the situation, by a lot, so thank you. But, do you have any suggestions on how to get at the information inside the Faraday middleware instance that gets created to handle the request? 

I was hoping to handle the request and response more programmatically than logging, and I can't think of a simple way to handle this that doesn't involve a race condition (like saving the response to a class variable and hoping to grab it right after a request, before the next request sets it).

**Comment by konklone** [comment]
I ended up going with the class variable approach, race conditions are probably not going to be a problem in practice. I generate a new Rubberband client on each request to my API, and I only insert the debug middleware if an explain flag is passed to my API, which would never be used by a client.

If you're at all curious to see what I mean, [here's an example](http://api.realtimecongress.org/api/v1/search/bills.json?apikey=68dfbd3a55924ce0ba92c16934b0a281&query=health&per_page=1&highlight=true&explain=true) of a search for bills about health care, with explain mode on. The "request" and "response" objects are the env[:body] of the ES request and response, parsed with Oj and then serialized again as part of the output. All that extra work only occurs when explain mode is on, so regular users won't take a performance hit when [explain mode is off](http://api.realtimecongress.org/api/v1/search/bills.json?apikey=68dfbd3a55924ce0ba92c16934b0a281&query=health&per_page=1&highlight=true).

[The logger I use](https://github.com/sunlightlabs/realtimecongress/blob/master/searchable.rb#L382) just stores it in a class variable:

``` ruby
class ExplainLogger < Faraday::Response::Middleware

  def self.last_request; @@last_request; end
  def self.last_response; @@last_response; end

  def call(env)
    # puts "request: #{env.inspect}\n\n"
    @@last_request = {
      body: env[:body] ? ::Oj::load(env[:body], mode: :compat) : nil, 
      url: env[:url].to_s
    }
    super
  end

  def on_complete(env)
    # puts "response: #{env.inspect}\n\n"
    @@last_response = {
      body: env[:body] ? ::Oj::load(env[:body], mode: :compat) : nil,
      url: env[:url].to_s
    }
  end
end
```

Since this resolves it for me, I'll mark the issue as closed. Any suggestions you have on how I could do this better are still welcome, of course. :) Thank you again!

**Comment by grantr** [comment]
@konklone I would not recommend generating a new client each request. That keeps the http client from using keepalive. If you want the ability to switch between debug and non-debug clients, keep two clients open and choose one at request time.

Additionally, if auto_discovery is on (it is on by default) then new clients will make an initial request to discover all nodes before making any other requests. So that would cause twice as many requests to elasticsearch as you expect. At the very least create clients with :auto_discovery => false.

**Comment by konklone** [comment]
Those are good points. And yes, I had finally just noticed those autodiscovery requests when setting up this logger. 

I'll look at what kind of refactoring it would take to keep an open connection, I think it'd be simple enough to do. I had actually already been meaning to take advantage of rubberband's autodiscovery feature (I'm using a cluster on EC2, and using the cloud-aws plugin to keep them in sync), so it would make a lot of sense for me to do what you're suggesting.
