### ISSUE TITLE
get_aliases ignores the index argument

### ISSUE THREAD

**Issue by erickt** [grantr/rubberband#39]
Here's the code:

```
def get_aliases(index=default_index, options={})
  index, type, options = extract_scope(options)
  execute(:get_aliases, index, options)
end
```

As you can see, `get_aliases` is ignoring the index that is getting passed in. In order to properly get the alias for a single index, you must do `client.get_aliases(nil, :index => 'index')`.

**Comment by grantr** [comment]
Fixed, thanks for the report!
