### ISSUE TITLE
Having some trouble getting started

### ISSUE THREAD

**Issue by kbaum** [grantr/rubberband#4]
Trying to perform the following search using rubberband, but I am unable to figure it out.
    curl -XGET http://localhost:12345/emails/_search -d '{
        "query": {
            "filtered": {
                "query": {"match_all": {}},
                "filter": {
                    "term": {"class": "order"}
                }
            }
        },
        "facets": {
            "from_domain": {
                "terms": {
                    "field": "from_domain",
                    "size": "500"
                }
            }
        }
    }'

Any examples of something like this i can look at?

Thanks!

**Comment by grantr** [comment]
Call the search method with a hash as the first argument. The hash should be the same as what you're passing to elasticsearch in the request body above.

I'm not able to test this right now, so this might have syntax errors. but this is the idea:

```
>> require 'elasticsearch'
>> es = ElasticSearch.new("localhost:12345", :index => 'emails')
>> result = es.search(Yajl::Parser.parse('{
  "query": {
      "filtered": {
          "query": {"match_all": {}},
          "filter": {
              "term": {"class": "order"}
          }
      }
  },
  "facets": {
      "from_domain": {
          "terms": {
              "field": "from_domain",
              "size": "500"
          }
      }
  }
}')
```

The result will be a Hits object which acts like an array of Hits but also has a total_entries method for compability with will_paginate.

See https://github.com/grantr/rubberband/blob/master/lib/elasticsearch/client/index.rb for examples of options that the search method takes.
