### ISSUE TITLE
index and type or defaults required 

### ISSUE THREAD

**Issue by pannous** [grantr/rubberband#43]
./test.rb 
/Users/me/.rvm/gems/ruby-1.9.3-p125/gems/rubberband-0.9.5/lib/elasticsearch/client/default_scope.rb:31:in `extract_required_scope': index and type or defaults required (RuntimeError)
    from /Users/me/.rvm/gems/ruby-1.9.3-p125/gems/rubberband-0.9.5/lib/elasticsearch/client/index.rb:7:in`index'
    from ./test.rb:6:in `<main>'

me:~/dialogues/rubberband$ cat test.rb 

require 'rubberband'
client = ElasticSearch.new(['elastico.xxxxx.com:9200/userindex_search'])
 client.index({:body => "elasticsearch is cool"}, :id => 1)  
 client.get("1")  
 client.search("body:elasticsearch")

**Comment by grantr** [comment]
Seems like a bug in the readme. Do you think this code should work? If so what should the default type be?
