### ISSUE TITLE
delete_by_query without type

### ISSUE THREAD

**Issue by brackxm** [grantr/rubberband#48]
Currently delete_by_query requires a type.
elasticsearch, however, does not require a type in the delete by query api.
example from http://www.elasticsearch.org/guide/reference/api/delete-by-query.html
curl -XDELETE 'http://localhost:9200/twitter/_query?q=user:kimchy'

**Comment by grantr** [comment]
Good point, this should change

**Comment by grantr** [comment]
Fixed in 3c3359b0698d3d2dadfc2b0dd10fede577146fe1 to be released in 0.9.8
