### ISSUE TITLE
index exists

### ISSUE THREAD

**Issue by brackxm** [grantr/rubberband#49]
add index exists api
example from http://www.elasticsearch.org/guide/reference/api/admin-indices-indices-exists.html
curl -XHEAD 'http://localhost:9200/twitter'

workaround:
client.index_status(:all)['indices'].keys.include? 'twitter'

**Comment by grantr** [comment]
Yes, I've definitely felt the ugliness of not having this available. I'll try to get this in.

**Comment by grantr** [comment]
added in 52b7adb674fa6237f8a82baba40ca420d2bc358d and will be released in 0.9.8
