### ISSUE TITLE
IndexProtocol does not pay attention to options.

### ISSUE THREAD

**Issue by infochimps** [grantr/rubberband#8]
Looking at the code for `IndexProtocol#index` in `rubberband/lib/elasticsearch/transport/base_protocol.rb` I notice that the `options`  arg passed to the method is never used for anything.

This usually isn't a big deal but it prevents one from using explicit routing features, parent/child indexing, the `op_type` method, &c. -- see the [ElasticSearch indexing API documentation](http://www.elasticsearch.com/docs/elasticsearch/rest_api/index/) for how such parameters are used.

The `IndexProtocol#index` method ultimately winds up calling a request method which (depending on how you're talking to ElasticSearch) is handled by something like `Transport::HTTP#request`.  This method does the right thing (it looks like) when you pass it some `params` so it looks like if `IndexProtocol#index` were to pass the proper `params` to the `request` method then all would be well -- the `params` would get translated into the query part of the generated URI.

This kind of error may also affect other actions besides index and other transport methods besides HTTP -- I ran into it trying to index a child document with a required routing parameter (because of a parent/child mapping).

**Comment by grantr** [comment]
yep, this is pretty annoying. Working on a fix. not complicated but its a good opportunity for some general cleanup.

**Comment by infochimps** [comment]
you're right it's a pretty simple fix -- i've patched in what i need in the copy i'm running.  the test suite for 0.0.6 is a little brittle right now so i'm having trouble running the tests (my feeling is that the rails part should be decoupled and only required when testing the activerecord extensions) or i would have just sent you a pull request.

rubberband is awesome btw!

**Comment by grantr** [comment]
I wouldn't call the test directory anything close to a suite. it's more like a test broom closet. :)

The tests are definitely not easy to run right now. I'd like to switch to rspec and use mocks where possible, then add some integration tests with live elasticsearch.

I also feel like the activerecord stuff should be moved to a rubberband-rails gem. I have some other rails-specific stuff i'd like to add (searchable models with activerecord2 find syntax) but it doesn't really belong in rubberband proper.

**Comment by grantr** [comment]
fixed in 636d8c27ef16744fe4a849163ca831ff8bcad08d
